# Generated by Django 3.0.6 on 2020-05-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
